#!/usr/bin/env python3
"""Join mirror_core.gs and Code.gs into the one file the owner pastes into Apps Script (no logic of its own)."""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "CryptoPulseV2_archive_sync.gs"


def build():
    core = (HERE / "mirror_core.gs").read_text()
    core = "\n".join(l for l in core.splitlines() if not l.startswith("if (typeof module !== 'undefined')")) + "\n"
    head = ("// GENERATED by research/archive/apps_script/build_single_file.py from mirror_core.gs + Code.gs. Do not edit here.\n"
            "// Paste this whole file into the Apps Script project as its only .gs file.\n\n")
    return head + core + "\n" + (HERE / "Code.gs").read_text()


if __name__ == "__main__":
    OUT.write_text(build())
    print(OUT, len(OUT.read_text()), "chars")
