// D1 evidence gathering -- READ ONLY, enforced in code: runQuery refuses
// anything that isn't a SELECT, independent of what any caller intends to
// pass it. Column names below were verified directly against the live
// production database in this and prior sessions, never guessed.

const CF_API = 'https://api.cloudflare.com/client/v4';

export async function runQuery(accountId, databaseId, token, sql, params = []) {
  if (!accountId || !databaseId || !token) return { ok: false, unavailable: true, reason: 'credentials unavailable' };
  const trimmed = sql.trim().toUpperCase();
  if (!trimmed.startsWith('SELECT')) {
    throw new Error(`Refusing to execute a non-SELECT statement in a read-only audit: ${sql.slice(0, 80)}`);
  }
  try {
    const res = await fetch(`${CF_API}/accounts/${accountId}/d1/database/${databaseId}/query`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ sql, params }),
    });
    const body = await res.json().catch(() => null);
    if (!res.ok || !body || body.success === false) {
      return { ok: false, unavailable: true, reason: `D1 query failed: ${res.status} ${JSON.stringify(body && body.errors)}` };
    }
    const results = (body.result && body.result[0] && body.result[0].results) || [];
    return { ok: true, unavailable: false, results };
  } catch (e) {
    return { ok: false, unavailable: true, reason: `D1 query threw: ${e.message}` };
  }
}

// All Analyst Relay submissions, newest first. Replaces
// getAllGeminiInvestigationsFull (which read gemini_investigations, the
// automated MI- table) -- that mechanism was removed entirely; Analyst
// Relay (analyst_relay_log) is now the sole investigation path. Pulls
// context_json/context_hash in the same query to avoid a second
// round-trip for whichever row turns out to be the successful one.
export async function getAllAnalystRelayEntries(accountId, databaseId, token) {
  const r = await runQuery(accountId, databaseId, token,
    `SELECT id, relay_id, candidate_id, assets_json, submitted_ts, raw_response_text, validation_status, catalysts_written, context_json, context_hash
     FROM analyst_relay_log ORDER BY submitted_ts DESC`);
  if (!r.ok) return r;
  return { ok: true, unavailable: false, rows: r.results };
}

export async function getAnalystRelayByRelayId(accountId, databaseId, token, relayId) {
  const r = await runQuery(accountId, databaseId, token,
    `SELECT id, relay_id, candidate_id, assets_json, submitted_ts, raw_response_text, validation_status, catalysts_written, context_json, context_hash
     FROM analyst_relay_log WHERE relay_id = ? ORDER BY submitted_ts DESC LIMIT 1`,
    [relayId]);
  if (!r.ok) return r;
  return { ok: true, unavailable: false, row: r.results[0] || null };
}

export async function getCatalystsForInvestigation(accountId, databaseId, token, investigationId) {
  const r = await runQuery(accountId, databaseId, token,
    `SELECT id, ts, coin, category, direction, source_url, discovery_timestamp, confidence, market_classification, investigation_id
     FROM coin_catalyst_log WHERE investigation_id = ? ORDER BY ts DESC`,
    [investigationId]);
  if (!r.ok) return r;
  return { ok: true, unavailable: false, rows: r.results };
}

// Latest resolved prediction across all three tables, newest overall wins
// (the task doesn't specify a single asset -- "the latest prediction
// generated by the current production Worker" is asset-agnostic).
export async function getLatestResolvedPrediction(accountId, databaseId, token) {
  const tables = [['BTC', 'predictions'], ['LINK', 'link_predictions'], ['ETH', 'eth_predictions']];
  const rows = [];
  for (const [coin, table] of tables) {
    const r = await runQuery(accountId, databaseId, token,
      `SELECT id, ts, resolved_ts, model_version, git_commit_sha FROM ${table} WHERE resolved_ts IS NOT NULL ORDER BY resolved_ts DESC LIMIT 1`);
    if (r.ok && r.results[0]) rows.push({ coin, ...r.results[0] });
    else if (!r.ok) return r; // surface the first genuine credential/query failure rather than silently dropping a table
  }
  if (rows.length === 0) return { ok: true, unavailable: false, row: null };
  rows.sort((a, b) => b.resolved_ts - a.resolved_ts);
  return { ok: true, unavailable: false, row: rows[0] };
}

// First selection_decisions row for the given coin AFTER the investigation
// fired, within a 24h window -- "the loop consumed this investigation and
// it showed up in the NEXT selection cycle", not just "a selection
// decision exists somewhere in D1 for this coin at some point" (a table
// existing is explicitly NOT sufficient per section 15).
export async function getSelectionDecisionAfter(accountId, databaseId, token, coin, sinceTs) {
  const r = await runQuery(accountId, databaseId, token,
    `SELECT id, ts, coin, horizon_hours, chosen_variant, chosen_p_up, lca_score, comparison_count, cleared_gate, reason, prediction_ts
     FROM selection_decisions WHERE coin = ? AND ts >= ? AND ts <= ? ORDER BY ts ASC LIMIT 1`,
    [coin, sinceTs, sinceTs + 24 * 3600 * 1000]);
  if (!r.ok) return r;
  return { ok: true, unavailable: false, row: r.results[0] || null };
}

export async function checkD1Reachable(accountId, databaseId, token) {
  const r = await runQuery(accountId, databaseId, token, `SELECT 1 as ok`);
  return r.ok && r.results && r.results[0] && r.results[0].ok === 1;
}
